const usersMocked = [
	{ username: 'Blibli#1', id: '' },
	{ username: '', id: '' },
	{ username: '', id: '123456' },
	{ username: '', id: '' },
	{ username: '', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: 'Blibli', id: '' },
	{ username: '', id: '' },
	{ username: '', id: '' },
	{ username: '', id: '' },
	{ username: '', id: '' },
	{ username: 'Blibli', id: '6P4I-snhy8uGZxkgAAAH' },
	{ username: 'Blibli', id: '6P4I-snhy8uGZxkgAAAH' },
	{ username: 'Blibli', id: '6P4I-snhy8uGZxkgAbcH' },
	{ username: 'Blibli#1', id: '6P4I-snhy8uGZxkgAAAH' },
	{ username: 'Blibli#1', id: '6P4I-snhy8uGZxkgAAAH' },
	{ username: '', id: '' },
];

export default usersMocked;
