name: Linter frontend

on: workflow_call

jobs:
  lint-frontend:
    name: Check lint frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.14.1

    - name: Install dependencies
      working-directory: frontend/
      run: npm install

    - name: Run linter
      working-directory: frontend/
      run: npm run lint
    
    - name: Copy .env.example in .env
      working-directory: frontend/
      run: cp .env.example .env

    - name: Run check svelte
      working-directory: frontend/
      run: npm run check

    - name: Forbidden tag
      working-directory: frontend/
      run: |
        if grep -rnw './src' -e 'svg' -e 'canvas' -e 'table'; then
          echo "Forbidden tags found."
          exit 1
        else
          echo "Not forbidden tags found"
        fi
