name: Linter frontend

on:
  push:
    paths: ['frontend/**']
    branches: [
      'feat/**', 'feature/**',
      'fix/**', 'hotfix/**',
      'facto/**', 'refactorisation/**'
    ]
  pull_request:
    branches: ['main']
    paths: ['frontend/**']

jobs:
  lint-frontend:
    name: Check lint frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.1

    - name: Install dependencies
      working-directory: frontend/
      run: npm install

    - name: Run linter
      working-directory: frontend/
      run: npm run lint

    - name: Run check svelte
      working-directory: frontend/
      run: npm run check
